version: '3.4'

services:
  sqlserverdirectus:
    container_name: sqlserverdirectus
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 2astazeY
        #MSSQL_DB: Northwind #Custom Image Environment Variable
        MSSQL_USER: directus_db_user #Custom Image Environment Variable
        MSSQL_PASSWORD: directus_db_p@ssw0rd #Custom Image Environment Variable
    ports:
        - 1434:1433 
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U $$MSSQL_USER -P $$MSSQL_PASSWORD -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s

